# SonarQube Configuration - Frontend
sonar.projectKey=recruitify-frontend
sonar.projectName=Recruitify Frontend
sonar.projectVersion=0.1.0
sonar.sources=src
sonar.tests=src/__test__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
# Pass token via env var SONAR_TOKEN or CLI -Dsonar.login=xxx

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.d.ts,**/public/**

# Coverage (Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
