import type { JobPosting } from './types';

export const mockJobs: JobPosting[] = [
  {
    id: 7781,
    title: 'Math Teacher',
    status: 'active',
    assignedToMe: true,
    category: 'Education',
    employmentType: 'Full Time',
    workApproach: 'Onsite',
    location: 'Riyadh',
    salary: '$80K - $100K',
    experience: '3+ years',
    license: 'Required',
    applicants: 121,
    openings: 3,
    addedAt: '14 April 2025',
  },
  {
    id: 7780,
    title: 'English Teacher',
    status: 'active',
    category: 'Education',
    employmentType: 'Part Time',
    workApproach: 'Hybrid',
    location: 'Riyadh',
    salary: '$60K - $80K',
    experience: '2+ years',
    license: 'Required',
    applicants: 84,
    openings: 4,
    addedAt: '14 April 2025',
  },
  {
    id: 7779,
    title: 'Biology Teacher',
    status: 'active',
    category: 'Science',
    employmentType: 'Part Time',
    workApproach: 'Onsite',
    location: 'Riyadh',
    salary: '$70K - $90K',
    experience: '3 years',
    license: 'Yes',
    applicants: 75,
    openings: 3,
    addedAt: '13 April 2025',
  },
  {
    id: 7778,
    title: 'Visual Arts Teacher',
    status: 'draft',
    category: 'Arts',
    employmentType: 'Full Time',
    workApproach: 'Onsite',
    location: 'Riyadh',
    salary: '$50K - $70K',
    experience: '1-3 years',
    license: 'No',
    applicants: 0,
    openings: 1,
    addedAt: '13 April 2025',
  },
  {
    id: 7777,
    title: 'Physics Teacher',
    status: 'completed',
    category: 'Science',
    employmentType: 'Part Time',
    workApproach: 'Remote',
    location: 'Riyadh',
    salary: '$80K - $100K',
    experience: '5 years',
    license: 'Yes',
    applicants: 98,
    openings: 10,
    addedAt: '11 April 2025',
  },
  {
    id: 7776,
    title: 'Humanities Teacher',
    status: 'completed',
    category: 'Humanities',
    employmentType: 'Full Time',
    workApproach: 'Hybrid',
    location: 'Riyadh',
    salary: '$75K - $95K',
    experience: '4 years',
    license: 'Required',
    applicants: 112,
    openings: 20,
    addedAt: '12 April 2025',
  },
];
