import type { JobPosting } from './types';

const sharedDetails = {
  availability: 'Full-time/part-time',
  workApproach: 'Remote',
  license: 'Required',
  experience: '3+ years',
  applicants: 154,
  about:
    'As a Senior Product Designer on the Accessibility team, you will establish accessible product practices, collaborate across teams, and improve inclusive user experiences.',
  responsibilities: [
    'Integrate accessibility best practices throughout the design process.',
    'Support designers through documentation, partnership, and review.',
    'Partner with research and engineering teams to improve product quality.',
  ],
  education: 'B.sc in Computer Science or any engineering subjects',
  skills: ['Product Design', 'UI/UX Design', 'Prototyping', 'Interaction Design', 'Wireframe', 'Design System'],
  qualifications: [
    '5-7 years of UX experience in an Enterprise or retail environment.',
    'Experience working with agile software development teams.',
    'Demonstrated ability to initiate and self-manage complex projects.',
  ],
};

export const mockJobs: JobPosting[] = [
  {
    ...sharedDetails,
    id: 1,
    title: 'Personal Assistant',
    category: 'Administrative',
    status: 'open',
    salary: '$80K - $100K',
    location: 'Canada',
    matched: 40,
    workApproach: 'Onsite',
  },
  {
    ...sharedDetails,
    id: 2,
    title: 'Junior HR Manager',
    category: 'Administrative',
    status: 'open',
    salary: '$80K - $100K',
    location: 'India',
    matched: 40,
    workApproach: 'Hybrid',
  },
  {
    ...sharedDetails,
    id: 3,
    title: 'Senior Product Designer',
    category: 'Product',
    status: 'hold',
    salary: '$80K - $100K',
    location: 'USA',
    matched: 40,
  },
  {
    ...sharedDetails,
    id: 4,
    title: 'Associate Product Designer',
    category: 'Marketing',
    status: 'closed',
    salary: '$80K - $100K',
    location: 'UK',
    matched: 40,
    workApproach: 'Onsite',
  },
  {
    ...sharedDetails,
    id: 5,
    title: 'Software Developer',
    category: 'Engineering',
    status: 'closed',
    salary: '$80K - $100K',
    location: 'UK',
    matched: 40,
  },
  {
    ...sharedDetails,
    id: 6,
    title: 'Customer Success Manager',
    category: 'Administrative',
    status: 'open',
    salary: '$80K - $100K',
    location: 'India',
    matched: 40,
  },
];
