# Server
server.address=0.0.0.0
server.port=8080


# Application
spring.application.name=web-api

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
ai.service.url=http://localhost:8000/analyze
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#SpringDoc OpenAPI Properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none

#Disable springdoc completely if it continues to cause issues
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.override-with-generic-response=false

# Container health check
management.endpoint.health.probes.enabled=true

#JWT Properties
jwt.secret=${JWT_SECRET:}
jwt.expirationMs=3600000
jwt.refreshExpirationMs=604800000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#image-kit
imagekit.url-endpoint=${IMAGEKIT_URL_ENDPOINT:}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY:}
imagekit.public-key=${IMAGEKIT_PUBLIC_KEY:}
