# Server
server.address=0.0.0.0
server.port=8080


# Application
spring.application.name=web-api

# Datasource
spring.datasource.url=jdbc:postgresql://recruitify-postgres-001.postgres.database.azure.com:5432/recruitify?sslmode=require
spring.datasource.username=recruitify
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#SpringDoc OpenAPI Properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none

#Disable springdoc completely if it continues to cause issues
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.override-with-generic-response=false

#JWT Properties
jwt.secret=rDjpL6NMo8pDZIHOT6Jfv0+qMDuR6hnuEDq+D9R+/1OHooaf3GMP4iLRW8Z5HhR6tg/rKQhtVM156AHgsD/tRw==
jwt.expirationMs=3600000
jwt.refreshExpirationMs=604800000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#image-kit
imagekit.url-endpoint =https://ik.imagekit.io/uvc58ihfu
imagekit.private-key=private_h7tCI126etRKSHn8Wz4/jZMZvd0=
imagekit.public-key=public_mU0z6rnFC32Bmk5tFYSYsiTx9aY=