version: "3.9"

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: recruitify-postgres
    environment:
      POSTGRES_USER: recruitify
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruitify
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruitify"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - recruitify-network

  sonar-db:
    image: sonarqube:lts-community
    container_name: recruitify-sonar
    ports:
      - "9000:9000"
    networks:
      - recruitify-network

volumes:
  postgresql-data:

networks:
  recruitify-network: